const Data=[
    {
        img:"/images/samurai.jpg",
        title:"Templete 1",
        desc:"Desc-1.....................",
        review: "⭐⭐⭐⭐⭐",
        sale:"100 sale",
        price:"$20",
        detail:"www.google.com",
        forward:"www.google.com",
    },
    {
        img:"/images/samurai.jpg",
        title:"Templete 2",
        desc:"Desc-2.....................",
        review: "⭐⭐⭐⭐",
        sale:"200 sale",
        price:"$30",
        detail:"www.google.com",
        forward:"www.google.com",
    },
    {
        img:"/images/samurai.jpg",
        title:"Templete 3",
        desc:"Desc-3.....................",
        review: "⭐⭐⭐",
        sale:"300 sale",
        price:"$40",
        detail:"www.google.com",
        forward:"www.google.com",
    },
    {
        img:"/images/samurai.jpg",
        title:"Templete 1",
        desc:"Desc-1.....................",
        review: "⭐⭐⭐⭐⭐",
        sale:"100 sale",
        price:"$20",
        detail:"www.google.com",
        forward:"www.google.com",
    },
    {
        img:"/images/samurai.jpg",
        title:"Templete 2",
        desc:"Desc-2.....................",
        review: "⭐⭐⭐⭐",
        sale:"200 sale",
        price:"$30",
        detail:"www.google.com",
        forward:"www.google.com",
    },
    {
        img:"/images/samurai.jpg",
        title:"Templete 2",
        desc:"Desc-2.....................",
        review: "⭐⭐⭐⭐",
        sale:"200 sale",
        price:"$30",
        detail:"www.google.com",
        forward:"www.google.com",
    },
];
export default Data;